### ISSUE TITLE
あれ、github actionsって組織アカウントでも無料で使えるんだっけ?を調査

### ISSUE THREAD

**Issue by ghost** [GreenAvenue/geranium#14]

**Comment by rothr4** [comment]
OK.
> GitHub ActionsはGitHub Free、GitHub Pro、GitHub Team、GitHub Enterprise Cloud、GitHub Oneで利用できます。

("Github Team" is included in "Github Organization")

Free.
>GitHub Actionsの支払いについて
>パブリックリポジトリでは、GitHub Actionsの利用は無料です。 プライベートリポジトリでは、それぞれのGitHubアカウントは使用している製品に応じて一定量の無料の分とストレージを受け取ります。 詳細は「GitHub Actions の支払いについて」を参照してください。
