### ISSUE TITLE
言語方針について相談する

### ISSUE THREAD

**Issue by ghost** [GreenAvenue/geranium#28]
以下でいきたい

- front/api
  - typescriptでいきたい(裏表で同じ型を使える)
- infra/その他の便利コマンド
  - Goでいきたい(いまのは流行りに乗ろうw)
  - 暫定対処や時間的な都合によってはBash
- document系
  - なるべくはplunUmlでいきたい
  - テキストデータとして図を管理できる
  - レビューがしやすい

**Comment by rothr4** [comment]
LGTM

**Comment by ghost** [comment]
Rust
