### ISSUE TITLE
クラウドフロントのYamlから費用を概算する方法を調査

### ISSUE THREAD

**Issue by ghost** [GreenAvenue/geranium#43]

**Comment by rothr4** [comment]
CLIでyaml指定するだけでいける。
が、AWSのアカウント持ってないと使えない。

以下、手順

## IAMポリシーの設定
CloudFormation : EstimateTemplateCost  
↑これをユーザに付与

## アクセスキーの発行
[認証情報] -> [アクセスキーの発行] を選択
- Access key ID
- Secret access key
の2つを取得

## awscliの設定
リージョンはテキトー
```
$ aws configure --profile myaws

AWS Access Key ID [None]: アクセスキー
AWS Secret Access Key [None]: シークレットキー
Default region name [None]: us-east-2
Default output format [None]: json
```

## awscliを実行
```
aws cloudformation --profile myaws \
estimate-template-cost --template-body file://cost_sample.yaml
```
## 結果の閲覧
↑のコマンド叩いて返ってきたURLを開けばOK
```
{
    "Url": "http://calculator.s3.amazonaws.com/calc5.html?key=XXXXXXXXXXXX"
}
```

## 画面サンプル
![view_cost_sample](https://user-images.githubusercontent.com/38580845/76651564-1b96cc00-65a8-11ea-9d2d-ea2a61773a44.png)

**Comment by rothr4** [comment]
ちなみに
> AWS Simple Monthly Calculator自体の利用料金は無料です。
