### ISSUE TITLE
要件定義周りの資料やりとりメモ

### ISSUE THREAD

**Issue by ghost** [GreenAvenue/geranium#59]
## 直近の要件定義のフローについて

1. 技術チームからフォーマットのサンプル資料を営業に投げる
2. 営業で埋められる範囲であらかじめ埋めてもらう
3. 営業と顧客で最終的に何を作りたいのかをアウトプットしてもらう
4. 最終的に何を作りたいのかを技術チームが受け取る
5. 技術的,工数的,値段的な実現可否の技術チームでのジャッジ
6. (調査機関をいただけると嬉しい。期間は調査対象の項目数に応じる)
7.  顧客に取捨選択をしてもらう
8. 各チームの合意が取れる。正式にキックオフ。

**Comment by ghost** [comment]
> フォーマットのサンプル資料

- 現時点で以下を想定
  - 実装項目一覧表
    - これは技術チーム側でおおよその作成します
    - こちらでジャッジできないものに関してはTODOで穴を埋めてもらう
  - UIフロー図
    -  ただのサンプルを渡すのでそれを参考に営業と顧客間で完成させて欲しい
  - 各画面のワイヤーフレーム一覧
    -  ただのサンプルを渡すのでそれを参考に営業と顧客間で完成させて欲しい

**Comment by rothr4** [comment]
> 直近の要件定義のフローについて

これ、営業向けにスプレッドシート化するわ。
