### ISSUE TITLE
開発ルールの相談

### ISSUE THREAD

**Issue by ghost** [GreenAvenue/geranium#61]

**Comment by ghost** [comment]
何か相談しておきたことがあれば。相談しませう。

**Comment by ghost** [comment]
- コーディング規約
    - 例のごとくlintに従う方針

**Comment by ghost** [comment]
- testコード
    - ビジネスロジックではなるべくやりたい
    - その他については、妥協もせざるを得ない気もしている

**Comment by rothr4** [comment]
- Githubのブランチ戦略
  - Gitflowが基本ルールで良いと思う。
  - 調査→開発でフェーズチェンジMTGやると思うからその時までに決めとこう

**Comment by rothr4** [comment]
あ、今は全部masterにマージしていくわ^-^
